version: '3'
services:

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: web-app
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: web-webserver
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: web-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'superpass321!'
      MYSQL_DATABASE: 'web'
      MYSQL_USER: 'web'
      MYSQL_PASSWORD: 'pass321!'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
